"use client"

import { useState } from "react"
import { Archive, Bell, ChevronDown, Clock3, FileCheck2, FileClock, FileText, Folder, FolderOpen, Grid2X2, HelpCircle, LayoutDashboard, List, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Users } from "lucide-react"

const documents = [
  { name: "Política de seguridad de la información", type: "PDF", owner: "María González", updated: "Hoy, 09:42", status: "Aprobado", color: "green", icon: ShieldCheck },
  { name: "Contrato marco proveedores 2025", type: "DOCX", owner: "Carlos Méndez", updated: "Ayer, 16:18", status: "En revisión", color: "amber", icon: FileClock },
  { name: "Manual de incorporación", type: "PDF", owner: "Ana López", updated: "12 jun 2025", status: "Aprobado", color: "green", icon: FileCheck2 },
  { name: "Informe auditoría interna Q2", type: "XLSX", owner: "Javier Ruiz", updated: "10 jun 2025", status: "Pendiente", color: "blue", icon: FileText },
  { name: "Procedimiento de compras", type: "DOCX", owner: "Sofía Martín", updated: "08 jun 2025", status: "Vencido", color: "red", icon: Clock3 },
]

const statusStyles: Record<string, string> = {
  green: "bg-teal-50 text-teal-700 ring-teal-200",
  amber: "bg-amber-50 text-amber-700 ring-amber-200",
  blue: "bg-sky-50 text-sky-700 ring-sky-200",
  red: "bg-rose-50 text-rose-700 ring-rose-200",
}

export default function Home() {
  const [view, setView] = useState<"grid" | "list">("list")
  const [activeNav, setActiveNav] = useState("Resumen")

  return (
    <main className="min-h-screen bg-[#f6faf9] text-[#153a39]">
      <aside className="fixed inset-y-0 left-0 z-20 hidden w-[238px] flex-col bg-[#087f7b] px-4 py-6 text-white lg:flex">
        <div className="flex items-center gap-3 px-3"><div className="flex size-9 items-center justify-center rounded-xl bg-white text-[#087f7b] shadow-sm"><FolderOpen className="size-5" /></div><div><p className="text-[17px] font-bold tracking-tight">NexoDocs</p><p className="text-[10px] uppercase tracking-[0.18em] text-teal-100">Gestión documental</p></div></div>
        <nav className="mt-12 flex flex-1 flex-col gap-1" aria-label="Navegación principal"><p className="px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-teal-100/70">Espacio de trabajo</p>{[{ label: "Resumen", icon: LayoutDashboard }, { label: "Mis documentos", icon: FileText }, { label: "Carpetas", icon: Folder }, { label: "Revisiones", icon: Clock3 }].map(({ label, icon: Icon }) => <button key={label} onClick={() => setActiveNav(label)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${activeNav === label ? "bg-white font-semibold text-[#087f7b] shadow-sm" : "text-teal-50 hover:bg-white/10"}`}><Icon className="size-[18px]" />{label}{label === "Revisiones" && <span className="ml-auto rounded-full bg-amber-300 px-2 py-0.5 text-[10px] font-bold text-amber-950">8</span>}</button>)}<p className="mt-8 px-3 pb-3 text-[10px] font-semibold uppercase tracking-[0.18em] text-teal-100/70">Administración</p>{[{ label: "Usuarios y equipos", icon: Users }, { label: "Actividad", icon: Archive }, { label: "Configuración", icon: Settings }].map(({ label, icon: Icon }) => <button key={label} onClick={() => setActiveNav(label)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${activeNav === label ? "bg-white font-semibold text-[#087f7b] shadow-sm" : "text-teal-50 hover:bg-white/10"}`}><Icon className="size-[18px]" />{label}</button>)}</nav>
        <div className="rounded-2xl bg-[#076f6c] p-4"><div className="flex items-center justify-between text-xs font-semibold"><span>Almacenamiento</span><span>68%</span></div><div className="mt-3 h-1.5 rounded-full bg-teal-900/40"><div className="h-1.5 w-[68%] rounded-full bg-teal-100" /></div><p className="mt-2 text-[11px] text-teal-100">6.8 GB de 10 GB utilizados</p></div>
        <div className="mt-5 flex items-center gap-3 px-2"><div className="flex size-9 items-center justify-center rounded-full bg-[#d5f5f1] text-xs font-bold text-[#087f7b]">LM</div><div className="min-w-0"><p className="truncate text-sm font-semibold">Laura Martínez</p><p className="truncate text-[11px] text-teal-100">Administradora</p></div><ChevronDown className="ml-auto size-4 text-teal-100" /></div>
      </aside>

      <section className="lg:pl-[238px]"><header className="flex h-[76px] items-center justify-between border-b border-[#dcebe8] bg-white px-6 lg:px-9"><div className="flex items-center gap-3 lg:hidden"><div className="flex size-9 items-center justify-center rounded-xl bg-[#087f7b] text-white"><FolderOpen className="size-5" /></div><span className="font-bold">NexoDocs</span></div><div className="relative hidden w-full max-w-[360px] md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#87a3a1]" /><input aria-label="Buscar documentos" placeholder="Buscar documentos..." className="h-10 w-full rounded-xl border border-[#dcebe8] bg-[#f8fbfa] pl-10 pr-4 text-sm outline-none transition placeholder:text-[#9ab0ae] focus:border-[#0f9d9a] focus:ring-2 focus:ring-[#0f9d9a]/15" /></div><div className="ml-auto flex items-center gap-4"><button className="relative rounded-lg p-2 text-[#5a7775] hover:bg-[#eef8f6]" aria-label="Notificaciones"><Bell className="size-5" /><span className="absolute right-1.5 top-1.5 size-2 rounded-full bg-[#f07b68] ring-2 ring-white" /></button><button className="rounded-lg p-2 text-[#5a7775] hover:bg-[#eef8f6]" aria-label="Ayuda"><HelpCircle className="size-5" /></button><div className="hidden h-7 w-px bg-[#dcebe8] sm:block" /><div className="hidden items-center gap-2 sm:flex"><div className="flex size-8 items-center justify-center rounded-full bg-[#d5f5f1] text-[11px] font-bold text-[#087f7b]">LM</div><ChevronDown className="size-4 text-[#71908e]" /></div></div></header>
        <div className="mx-auto max-w-[1440px] px-6 py-8 lg:px-9"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-[#0f9d9a]">Jueves, 19 de junio de 2025</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-[#163a39]">Buenos días, Laura</h1><p className="mt-2 text-sm text-[#6b8583]">Esto es lo que está ocurriendo en tu espacio de trabajo.</p></div><button className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#0f9d9a] px-5 text-sm font-semibold text-white shadow-[0_6px_18px_rgba(15,157,154,0.2)] transition hover:bg-[#087f7b]"><Plus className="size-4" />Nuevo documento</button></div>
          <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Total documentos", value: "1,248", detail: "+12.5% este mes", icon: FileText, tone: "teal" }, { label: "Pendientes de revisión", value: "24", detail: "8 requieren atención", icon: FileClock, tone: "amber" }, { label: "Aprobados", value: "1,176", detail: "94.2% del total", icon: FileCheck2, tone: "green" }, { label: "Por vencer", value: "12", detail: "En los próximos 30 días", icon: Clock3, tone: "rose" }].map(({ label, value, detail, icon: Icon, tone }) => <div key={label} className="rounded-2xl border border-[#dcebe8] bg-white p-5 shadow-[0_2px_8px_rgba(17,71,68,0.03)]"><div className="flex items-start justify-between"><div className={`flex size-10 items-center justify-center rounded-xl ${tone === "teal" ? "bg-[#dff7f3] text-[#0f9d9a]" : tone === "amber" ? "bg-amber-50 text-amber-600" : tone === "green" ? "bg-emerald-50 text-emerald-600" : "bg-rose-50 text-rose-500"}`}><Icon className="size-5" /></div><MoreHorizontal className="size-5 text-[#a2b8b6]" /></div><p className="mt-5 text-sm text-[#6b8583]">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight text-[#163a39]">{value}</p><p className={`mt-2 text-xs font-medium ${tone === "amber" || tone === "rose" ? "text-[#c98732]" : "text-[#0f9d9a]"}`}>{detail}</p></div>)}</div>
          <div className="mt-8 grid gap-6 xl:grid-cols-[1fr_330px]"><div className="min-w-0 rounded-2xl border border-[#dcebe8] bg-white shadow-[0_2px_8px_rgba(17,71,68,0.03)]"><div className="flex flex-col gap-4 border-b border-[#edf3f1] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-[#163a39]">Documentos recientes</h2><p className="mt-1 text-xs text-[#78918f]">Gestiona y consulta los últimos documentos modificados</p></div><div className="flex items-center gap-2"><button className="inline-flex h-9 items-center gap-2 rounded-lg border border-[#dcebe8] px-3 text-xs font-semibold text-[#4e706d] hover:bg-[#f4faf9]"><List className="size-4" />Filtros</button><div className="flex rounded-lg border border-[#dcebe8] p-0.5"><button onClick={() => setView("list")} className={`rounded-md p-1.5 ${view === "list" ? "bg-[#dff7f3] text-[#087f7b]" : "text-[#8da5a3]"}`} aria-label="Vista de lista"><List className="size-4" /></button><button onClick={() => setView("grid")} className={`rounded-md p-1.5 ${view === "grid" ? "bg-[#dff7f3] text-[#087f7b]" : "text-[#8da5a3]"}`} aria-label="Vista de cuadrícula"><Grid2X2 className="size-4" /></button></div></div></div><div className={view === "grid" ? "grid gap-3 p-4 sm:grid-cols-2" : "divide-y divide-[#edf3f1]"}>{documents.map((doc) => { const Icon = doc.icon; return <div key={doc.name} className={view === "grid" ? "rounded-xl border border-[#e5efed] p-4 hover:border-[#8edbd5]" : "flex items-center gap-4 px-5 py-4 hover:bg-[#fbfefd]"}><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#eef8f6] text-[#0f9d9a]"><Icon className="size-5" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#244b49]">{doc.name}</p><p className="mt-1 text-xs text-[#8aa19f]">{doc.type} · {doc.owner} · {doc.updated}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[11px] font-semibold ring-1 ring-inset ${statusStyles[doc.color]}`}>{doc.status}</span><button className="shrink-0 text-[#9bb0ae] hover:text-[#087f7b]" aria-label={`Más opciones para ${doc.name}`}><MoreHorizontal className="size-5" /></button></div> })}</div><div className="border-t border-[#edf3f1] px-5 py-4"><button className="text-xs font-semibold text-[#0f9d9a] hover:text-[#087f7b]">Ver todos los documentos →</button></div></div>
            <div className="rounded-2xl border border-[#dcebe8] bg-white shadow-[0_2px_8px_rgba(17,71,68,0.03)]"><div className="flex items-center justify-between border-b border-[#edf3f1] p-5"><div><h2 className="font-bold text-[#163a39]">Actividad reciente</h2><p className="mt-1 text-xs text-[#78918f]">Últimas acciones del equipo</p></div><button className="text-xs font-semibold text-[#0f9d9a]">Ver todo</button></div><div className="flex flex-col gap-5 p-5">{[{ initials: "CM", text: "Carlos Méndez aprobó", doc: "Guía de marca 2025", time: "Hace 18 min", tone: "bg-amber-100 text-amber-700" }, { initials: "AL", text: "Ana López subió", doc: "Manual de incorporación", time: "Hace 1 h", tone: "bg-sky-100 text-sky-700" }, { initials: "JR", text: "Javier Ruiz comentó en", doc: "Informe auditoría interna", time: "Hace 2 h", tone: "bg-violet-100 text-violet-700" }, { initials: "SG", text: "Sofía García compartió", doc: "Procedimiento de compras", time: "Ayer, 16:42", tone: "bg-rose-100 text-rose-700" }].map((item) => <div key={item.initials + item.time} className="flex gap-3"><div className={`flex size-8 shrink-0 items-center justify-center rounded-full text-[10px] font-bold ${item.tone}`}>{item.initials}</div><div className="min-w-0"><p className="text-xs leading-5 text-[#55716f]">{item.text} <span className="font-semibold text-[#214b48]">{item.doc}</span></p><p className="mt-0.5 text-[11px] text-[#9aafad]">{item.time}</p></div></div>)}</div></div></div>
          <div className="mt-6 flex items-center gap-3 rounded-2xl border border-[#bfeae5] bg-[#eafaf7] px-5 py-4"><div className="flex size-9 items-center justify-center rounded-xl bg-white text-[#0f9d9a]"><ShieldCheck className="size-5" /></div><div><p className="text-sm font-semibold text-[#17635f]">Tu espacio está protegido</p><p className="mt-0.5 text-xs text-[#4b817d]">Todos tus documentos están cifrados y cuentan con control de acceso.</p></div><button className="ml-auto hidden text-xs font-semibold text-[#087f7b] sm:block">Ver configuración</button></div>
        </div>
      </section>
    </main>
  )
}
