server:
  port: 8080

spring:
  application:
    name: sistema-gestion

  # Configuración de Base de Datos PostgreSQL
  datasource:
    url: jdbc:postgresql://ep-fragrant-leaf-aewqacgw-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_DuPM8ehnoLT5
    driver-class-name: org.postgresql.Driver

  # Configuración de JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update # Cambia a 'none' o 'validate' en producción
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuración de Swagger / OpenAPI 3
# Configuración de Swagger / OpenAPI 3
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    use-root-path: true
    operations-sorter: method
    tags-sorter: alpha

# Parámetros personalizados para JWT (Opcional si los lees con @Value)
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 28800000 # 8 horas en milisegundos